apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  namespace: drupal
spec:
  selector:
    app: drupal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort